### ISSUE TITLE
Editing registers results in a blank buffer

### ISSUE THREAD

**Issue by amadeus** [rbong/vim-buffest#2]
It appears this plugin isn't working?

[video example](http://wtf.amadeus.wtf/monosnap/screencast_2019-03-07_13-33-41.mp4)

As you can see in this video, I set some text to the `a` register, I can paste just fine, but when I try to edit via `:Regsplit`, the temp buffer is empty?

Or maybe I am missing something :X

**Comment by rbong** [comment]
You're not missing anything, it looks like it should work to me. Can you try to disable everything else in your `.vimrc` and see if that fixes it? If that doesn't work, what OS is this on? What do you get from `vim --version`?

**Comment by amadeus** [comment]
I went to start testing out why it might be failing, and it appears to be working now :X 

So will close this for now since there's nothing to fix, lol

**Comment by rbong** [comment]
Well, glad it's working. Feel free to reopen if it happens again.
